export const CONNECTION_TYPES = {
  SET_CURRENT_USER_CONNECTION_STATUS:
    "connection/SET_CURRENT_USER_CONNECTION_STATUS",
  GET_FRIEND_CONNECTION_STATUS: "connection/GET_FRIEND_CONNECTION_STATUS",
  CONNECTION_STATUS_SUCCESS: "connection/CONNECTION_STATUS_SUCCESS",
  CONNECTION_STATUS_ERROR: "connection/CONNECTION_STATUS_ERROR",
  SET_FRIEND_CONNECTION_STATUS: "connection/SET_FRIEND_CONNECTION_STATUS",
};
